markdown: redcarpet
pygments: true
permalink: date
lsi: true
exclude: ['README.md', 'README_FOR_COLLABORATORS.markdown', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'LICENSE']
production: false
paginate: 10

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
